language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - tools

    - build-tools-29.0.6

    - android-29
    - sys-img-armeabi-v7a-android-29

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    
before_install:
  - yes | sdkmanager "platforms;android-27"
  - pip install --user codecov

script:
    - ./gradlew connectedAndroidTest coveralls
#   - ./gradlew build jacocoTestReport
#   - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
